#!/bin/bash
dpkg-deb -bZgzip projects/Fallout_4_Slider debs
dpkg-deb -bZgzip projects/JassalJeevan_Icon_Pack debs
dpkg-deb -bZgzip projects/The_Division_Slider debs
dpkg-deb -bZgzip projects/Germany_4-Star_Slider debs
dpkg-deb -bZgzip projects/Assassins_Creed_Volume_HUD debs
dpkg-deb -bZgzip projects/Danny_Phantom_Boot_Logo debs
dpkg-deb -bZgzip projects/Reba_McEntire_Boot_Logo debs
dpkg-deb -bZgzip projects/Christian_Fish_Boot_Logo debs
dpkg-deb -bZgzip projects/_116_Clique_Boot_Logo debs
dpkg-deb -bZgzip projects/Slytherin_Theme_Update debs
dpkg-deb -bZgzip projects/Bayern_Munich_Volume_HUD debs
dpkg-deb -bZgzip projects/Christian_Fish_Cross_Boot_Logo debs
dpkg-deb -bZgzip projects/Christian_Fish_IXOYE_Boot_Logo debs
dpkg-deb -bZgzip projects/_007_Slider debs
dpkg-deb -bZgzip projects/Juggernog_Slider debs
dpkg-deb -bZgzip projects/Dogmeat_Slider debs
dpkg-deb -bZgzip projects/Need_For_Speed_Slider debs
dpkg-deb -bZgzip projects/NBI_Boot_Logo debs
dpkg-deb -bZgzip projects/Life_Is_Strange_Slider debs
dpkg-deb -bZgzip projects/Beyond_Two_Souls_Slider debs
dpkg-deb -bZgzip projects/Tigres_UANL_Slider debs
dpkg-deb -bZgzip projects/Apple_Watch_Slider debs
dpkg-deb -bZgzip projects/_6_God_Hands_Slider debs
dpkg-deb -bZgzip projects/_300_Logo_Slider debs
dpkg-deb -bZgzip projects/AS_Roma_Slider debs
dpkg-deb -bZgzip projects/AC_Milan_Slider debs
dpkg-deb -bZgzip projects/ACC_Slider debs
dpkg-deb -bZgzip projects/ACF_Fiorentina_Slider debs
dpkg-deb -bZgzip projects/Assassins_Creed_Power_Off debs
dpkg-deb -bZgzip projects/Baschi_Verdi_Power_Off debs
dpkg-deb -bZgzip projects/FC_Barcelona_Power_Off debs
dpkg-deb -bZgzip projects/Man_U_Power_Off debs
dpkg-deb -bZgzip projects/Mercedes_Benz_Power_Off debs
dpkg-deb -bZgzip projects/Ant_Man_Slider debs
dpkg-deb -bZgzip projects/Apple_Swift_Slider debs
dpkg-deb -bZgzip projects/Arden_Hills_Logo_Slider debs
dpkg-deb -bZgzip projects/Argentina_World_Cup_Slider debs
dpkg-deb -bZgzip projects/Arsenal_FC_Slider debs
dpkg-deb -bZgzip projects/ASAP_Rocky_Slider debs
dpkg-deb -bZgzip projects/Assassins_Creed_Syndicate_Slider debs
# dpkg-deb -bZgzip projects/<project name> <output folder>
